import type { Repo } from './types'

export const seedRepos: Repo[] = [
  {
    id: 'raycast-extensions',
    owner: 'raycast',
    name: 'extensions',
    description: 'Community extensions for a launcher that keeps your tools close.',
    summary: 'A deep catalog of focused integrations. Useful as a reference for extension APIs and small, composable developer workflows.',
    language: 'TypeScript',
    languageColor: '#3178c6',
    tags: ['developer-tools', 'automation'],
    status: 'Active',
    updated: '2d ago',
    updatedAt: 2,
    project: 'Daily driver',
    note: 'Review extension API patterns when I need a new integration.',
    isPinned: true,
    githubUrl: 'https://github.com/raycast/extensions',
    readme: ['# Extensions', 'The open-source extension store for Raycast.', 'Browse, install, and build small tools that turn repeated actions into one command.'],
    files: ['extensions', 'CONTRIBUTING.md', 'README.md', 'package.json', 'tsconfig.json'],
    lastRelease: 'v1.92.0',
  },
  {
    id: 'zed',
    owner: 'zed-industries',
    name: 'zed',
    description: 'A high-performance, multiplayer code editor from the creators of Atom.',
    summary: 'A fast native editor with a strong systems foundation. Worth revisiting when evaluating editor architecture, collaboration, or Rust UI patterns.',
    language: 'Rust',
    languageColor: '#dea584',
    tags: ['editor', 'rust', 'collaboration'],
    status: 'Active',
    updated: '3d ago',
    updatedAt: 3,
    project: 'Editors',
    note: 'The native rendering model is the interesting part here.',
    isPinned: true,
    githubUrl: 'https://github.com/zed-industries/zed',
    readme: ['# Zed', 'Zed is a next-generation code editor designed for speed and collaboration.', 'It is built in Rust and designed around a GPU-accelerated interface.'],
    files: ['crates', 'docs', 'assets', 'Cargo.toml', 'LICENSE', 'README.md'],
    lastRelease: 'v0.213.0',
  },
  {
    id: 'coolify',
    owner: 'coollabsio',
    name: 'coolify',
    description: 'An open-source and self-hostable deployment platform.',
    summary: 'A practical deployment surface for teams that want control without rebuilding every platform primitive themselves.',
    language: 'PHP',
    languageColor: '#777bb4',
    tags: ['self-hosted', 'devops', 'platform'],
    status: 'Active',
    updated: '5d ago',
    updatedAt: 5,
    project: 'Homelab',
    note: 'Compare the setup experience with my current Docker notes.',
    isPinned: false,
    githubUrl: 'https://github.com/coollabsio/coolify',
    readme: ['# Coolify', 'An open-source and self-hostable alternative to Heroku, Netlify, and Vercel.', 'Deploy your full-stack applications on your own hardware.'],
    files: ['app', 'bootstrap', 'docker', 'resources', 'routes', 'composer.json'],
    lastRelease: 'v4.0.0-beta.380',
  },
  {
    id: 'glow',
    owner: 'charmbracelet',
    name: 'glow',
    description: 'Render markdown on the CLI, with style.',
    summary: 'A small, opinionated terminal reader. A useful reference for delightful CLI defaults and readable output without a browser.',
    language: 'Go',
    languageColor: '#00add8',
    tags: ['cli', 'markdown', 'tui'],
    status: 'Active',
    updated: '1w ago',
    updatedAt: 7,
    project: 'Daily driver',
    note: 'Keep the keyboard shortcuts in mind for the terminal deck.',
    isPinned: true,
    githubUrl: 'https://github.com/charmbracelet/glow',
    readme: ['# Glow', 'Render markdown on the CLI, with style.', 'Glow is a command-line tool that helps you read markdown files in your terminal.'],
    files: ['cmd', 'glamour', 'internal', 'main.go', 'go.mod', 'README.md'],
    lastRelease: 'v2.0.0',
  },
  {
    id: 'uv',
    owner: 'astral-sh',
    name: 'uv',
    description: 'An extremely fast Python package and project manager, written in Rust.',
    summary: 'A single sharp tool for the Python workflow. Its project model and speed make it a strong candidate for repeatable local automation.',
    language: 'Rust',
    languageColor: '#dea584',
    tags: ['python', 'tooling', 'rust'],
    status: 'Active',
    updated: '1w ago',
    updatedAt: 8,
    project: 'Toolbox',
    note: 'Try this for a clean dependency story in the next Python utility.',
    isPinned: false,
    githubUrl: 'https://github.com/astral-sh/uv',
    readme: ['# uv', 'An extremely fast Python package and project manager, written in Rust.', 'uv is designed to replace several tools in the Python packaging workflow.'],
    files: ['crates', 'docs', 'python', 'Cargo.toml', 'CONTRIBUTING.md', 'README.md'],
    lastRelease: '0.8.14',
  },
  {
    id: 'lazygit',
    owner: 'jesseduffield',
    name: 'lazygit',
    description: 'A simple terminal UI for git commands, written in Go.',
    summary: 'A focused example of how far a keyboard-first surface can go when every action is close, visible, and reversible.',
    language: 'Go',
    languageColor: '#00add8',
    tags: ['git', 'tui', 'workflow'],
    status: 'Active',
    updated: '2w ago',
    updatedAt: 14,
    project: 'Daily driver',
    note: 'The panel model is a good reference for a future git dashboard.',
    isPinned: false,
    githubUrl: 'https://github.com/jesseduffield/lazygit',
    readme: ['# lazygit', 'A simple terminal UI for git commands.', 'The goal is to make git operations easier to discover without hiding the underlying model.'],
    files: ['cmd', 'pkg', 'docs', 'go.mod', 'main.go', 'README.md'],
    lastRelease: 'v0.52.0',
  },
  {
    id: 'libsql',
    owner: 'tursodatabase',
    name: 'libsql',
    description: 'SQLite fork optimized for remote and edge workloads.',
    summary: 'A useful branch in the local-first database conversation: familiar SQL semantics with a path toward replication and edge deployment.',
    language: 'Rust',
    languageColor: '#dea584',
    tags: ['databases', 'edge', 'local-first'],
    status: 'Needs review',
    updated: '3w ago',
    updatedAt: 21,
    project: 'Architecture',
    note: 'Read the replication story before choosing a sync layer.',
    isPinned: false,
    githubUrl: 'https://github.com/tursodatabase/libsql',
    readme: ['# libSQL', 'libSQL is an embeddable SQL database based on SQLite.', 'It adds features for distributed and edge-first applications while keeping the SQLite core familiar.'],
    files: ['libsql', 'libsql-server', 'docs', 'Makefile', 'Cargo.toml', 'README.md'],
    lastRelease: '0.9.31',
  },
  {
    id: 'immich',
    owner: 'immich-app',
    name: 'immich',
    description: 'High performance self-hosted photo and video management solution.',
    summary: 'A mature self-hosted product surface with a lot to learn from around sync, background jobs, and a polished local-first experience.',
    language: 'TypeScript',
    languageColor: '#3178c6',
    tags: ['self-hosted', 'privacy', 'media'],
    status: 'Needs review',
    updated: '1mo ago',
    updatedAt: 30,
    project: 'Homelab',
    note: 'Check backup and migration paths before spinning this up.',
    isPinned: false,
    githubUrl: 'https://github.com/immich-app/immich',
    readme: ['# Immich', 'Self-hosted photo and video management solution.', 'A private library for media, search, sharing, and backups.'],
    files: ['machine-learning', 'server', 'web', 'docker', 'package.json', 'README.md'],
    lastRelease: 'v1.142.1',
  },
  {
    id: 'svelte',
    owner: 'sveltejs',
    name: 'svelte',
    description: 'Cybernetically enhanced web apps, compiled to tiny JavaScript.',
    summary: 'A compact compiler-led approach to UI. Keep this one around for ideas that make the browser do less work at runtime.',
    language: 'TypeScript',
    languageColor: '#3178c6',
    tags: ['frontend', 'compiler', 'framework'],
    status: 'Active',
    updated: '1mo ago',
    updatedAt: 35,
    project: 'Toolbox',
    note: 'Compare the compile-time trade-offs with the current app stack.',
    isPinned: false,
    githubUrl: 'https://github.com/sveltejs/svelte',
    readme: ['# Svelte', 'Svelte is a tool for building web applications.', 'It uses a compiler to turn declarative components into optimized JavaScript.'],
    files: ['packages', 'documentation', 'scripts', 'LICENSE.md', 'package.json', 'README.md'],
    lastRelease: 'v5.38.7',
  },
  {
    id: 'neovim',
    owner: 'neovim',
    name: 'neovim',
    description: 'A hyperextensible Vim-based text editor.',
    summary: 'A long-lived reference for making a powerful tool feel personal. The plugin and configuration model is the real library here.',
    language: 'C',
    languageColor: '#555555',
    tags: ['editor', 'terminal', 'extensible'],
    status: 'Active',
    updated: '2mo ago',
    updatedAt: 60,
    project: 'Editors',
    note: 'Keep the API docs nearby for editor integrations.',
    isPinned: false,
    githubUrl: 'https://github.com/neovim/neovim',
    readme: ['# Neovim', 'Neovim is a hyperextensible Vim-based text editor.', 'It focuses on extensibility, usability, and an asynchronous architecture.'],
    files: ['src', 'runtime', 'test', 'CMakeLists.txt', 'LICENSE', 'README.md'],
    lastRelease: 'v0.11.3',
  },
  {
    id: 'memos',
    owner: 'usememos',
    name: 'memos',
    description: 'An open-source, self-hosted memo hub with Markdown support.',
    summary: 'A small personal knowledge surface that keeps the writing path short and the data portable.',
    language: 'Go',
    languageColor: '#00add8',
    tags: ['notes', 'self-hosted', 'markdown'],
    status: 'Archived',
    updated: '4mo ago',
    updatedAt: 120,
    project: 'Notes',
    note: 'Decide whether the migration path is worth keeping this star.',
    isPinned: false,
    githubUrl: 'https://github.com/usememos/memos',
    readme: ['# Memos', 'An open-source, self-hosted memo hub.', 'Write and organize short notes in a calm, portable workspace.'],
    files: ['api', 'common', 'server', 'web', 'go.mod', 'README.md'],
    lastRelease: 'v0.24.0',
  },
  {
    id: 'awesome',
    owner: 'sindresorhus',
    name: 'awesome',
    description: 'Curated lists of tools, libraries, and ideas worth keeping close.',
    summary: 'The index of indexes. Useful when a half-remembered tool needs a path back into the wider ecosystem.',
    language: 'Markdown',
    languageColor: '#6f42c1',
    tags: ['curated', 'reference', 'lists'],
    status: 'Needs review',
    updated: '6mo ago',
    updatedAt: 180,
    project: 'Reference',
    note: 'Keep only if the categorized lists remain useful after import.',
    isPinned: false,
    githubUrl: 'https://github.com/sindresorhus/awesome',
    readme: ['# Awesome', 'A curated list of awesome lists.', 'A starting point for discovering focused collections across software and beyond.'],
    files: ['readme.md', 'contributing.md', 'license'],
    lastRelease: 'No releases',
  },
]

export const sectionMeta = {
  library: { title: 'Your library', subtitle: 'A working memory for the repos you meant to come back to.' },
  repos: { title: 'My repos', subtitle: 'Your own repositories, separate from the stars you are collecting.' },
  projects: { title: 'Projects', subtitle: 'Group the sparks by the work they might unlock.' },
  explore: { title: 'Explore', subtitle: 'Find new tools without losing the context behind the old ones.' },
  releases: { title: 'Releases', subtitle: 'Keep the repos you care about close to their next useful version.' },
} as const
